- name: be sure bash_aliases is configured
  template: src=bash_aliases.j2 dest={{ ansible_env.HOME }}/.bash_aliases owner={{ ansible_user_id }}

- include: bash_aliases.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: ensure ssh directory exists
  file: path={{ ansible_env.HOME }}/.ssh state=directory

- name: be sure ssh is configured
  copy: src=ssh_config dest={{ ansible_env.HOME }}/.ssh/config owner={{ ansible_user_id }}
