- name: ensure ack is installed
  apt: name=ack-grep state=present
  sudo: yes

- name: be sure ack is ack and not ack-grep
  command: dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
  sudo: yes
  ignore_errors: True
