" Configuration file for vim
set modelines=0		" CVE-2007-2438

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility

""""""""""""""""""""""""""""""""""
" NeoBundle Plugin Manager Stuff "
""""""""""""""""""""""""""""""""""
set runtimepath+=~/.vim/bundle/vundle.vim/

let vundle_readme=expand('~/.vim/bundle/vundle.vim/README.md')

if !filereadable(vundle_readme)
  " install vundle
  silent !mkdir -p ~/.vim/bundle
  silent !git clone https://github.com/VundleVim/Vundle.vim ~/.vim/bundle/vundle.vim/
endif

call vundle#begin(expand('~/.vim/bundle'))
Plugin 'VundleVim/Vundle.vim'

" Plugins Installation
Plugin 'tomasr/molokai'
Plugin 'scrooloose/syntastic'

call vundle#end()

filetype plugin indent on

""""""""""""""""""""""""""""""""
" Tab and indentation settings "
""""""""""""""""""""""""""""""""
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set softtabstop=4
set smarttab

set backspace=eol,start,indent

"""""""""""""""""""""""
" Don't create backup "
"""""""""""""""""""""""
set nobackup
set nowritebackup
set noswapfile

"""""""""""""""""""
" Search settings "
"""""""""""""""""""
set hlsearch
set incsearch
set ignorecase

"""""""""""""""""""
" Visual settings "
"""""""""""""""""""
" use this TRY..CATCH to avoid 'press enter to continue' in vim installation
try
    colorscheme molokai
catch
endtry

syntax on

" highlight current line
set cursorline
highlight CursorLine ctermbg=237

" show linenumber
set nu

" colors
set t_Co=256

""""""""""""
" Commands "
""""""""""""
" Save with root privilege
command Wroot :execute ':silent w !sudo tee % > /dev/null' | :edit!

""""""""""
" Abbrev "
""""""""""
" Or I use this abbrevs or remove my shift key
cnoreabbrev W! w!
cnoreabbrev Q! q!
cnoreabbrev Qall! qall!
cnoreabbrev Wq wq
cnoreabbrev Wa wa
cnoreabbrev wQ wq
cnoreabbrev WQ wq
cnoreabbrev W w
cnoreabbrev Q q
cnoreabbrev Qall qall

"""""""""""""""""
" Auto commands "
"""""""""""""""""
" remove trailing whitespaces
autocmd BufWritePre * :%s/\s\+$//e

" show colorcolumn for column 80 in python files
augroup python
    au!
    autocmd FileType python set colorcolumn=80
augroup END

" auto syntax for *.md files
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

""""""""""""""""""""
" Plugins Settings "
""""""""""""""""""""
" Netrw
let g:netrw_list_hide= '.*\.swp$,.*\.pyc,__pycache__'
let g:netrw_localrmdir="rm -r"

"" Syntastic
let g:syntastic_always_populate_loc_list=1
let g:syntastic_error_symbol='✗'
let g:syntastic_warning_symbol='⚠'
let g:syntastic_style_error_symbol = '✗'
let g:syntastic_style_warning_symbol = '⚠'
let g:syntastic_auto_loc_list=1
let g:syntastic_aggregate_errors = 1
let g:syntastic_python_checkers=['python', 'flake8']
