- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.arch.yml
  when: ansible_pkg_mgr == 'pacman'

- name: be sure vim is configured
  copy: src=vimrc dest={{ ansible_env.HOME }}/.vimrc owner={{ ansible_user_id }}

- name: be sure all plugins is installed
  command: vim +PlugInstall! +qall
